"""Unit tests for pure helpers in `micoo.main`."""

from __future__ import annotations

from pathlib import Path

import pytest
from git import Repo

from micoo import main as micoo_main


def _seed(path: Path, names: list[str]) -> None:
    path.mkdir(parents=True, exist_ok=True)
    repo = Repo.init(path)
    for name in names:
        (path / f"{name}.mise.toml").write_text(f"# {name}\n", encoding="utf-8")
    if names:
        repo.index.add([f"{name}.mise.toml" for name in names])
        repo.index.commit("seed")


def test_ensure_repository_exists_false(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Test `ensure_repository_exists` when the path is absent.

    Given:
        - `repository_path` points at a non-existent directory.
    When:
        - `ensure_repository_exists()` is called.
    Then:
        - It returns False.
    """
    monkeypatch.setattr(micoo_main, "repository_path", tmp_path / "absent")
    assert micoo_main.ensure_repository_exists() is False


def test_ensure_repository_exists_true(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Test `ensure_repository_exists` when the path is present.

    Given:
        - `repository_path` points at an existing directory.
    When:
        - `ensure_repository_exists()` is called.
    Then:
        - It returns True.
    """
    monkeypatch.setattr(micoo_main, "repository_path", tmp_path)
    assert micoo_main.ensure_repository_exists() is True


def test_get_available_cookbooks_sorted(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Test `get_available_cookbooks` returns names sorted without extension.

    Given:
        - The repository contains `node.mise.toml` and `python.mise.toml`.
    When:
        - `get_available_cookbooks()` is called.
    Then:
        - It returns `["node", "python"]` in sorted order.
    """
    _seed(tmp_path, ["python", "node"])
    monkeypatch.setattr(micoo_main, "repository_path", tmp_path)
    assert micoo_main.get_available_cookbooks() == ["node", "python"]


def test_get_available_cookbooks_empty(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Test `get_available_cookbooks` on an empty repository.

    Given:
        - The repository contains no cookbook files.
    When:
        - `get_available_cookbooks()` is called.
    Then:
        - It returns an empty list.
    """
    monkeypatch.setattr(micoo_main, "repository_path", tmp_path)
    assert micoo_main.get_available_cookbooks() == []


def test_prepare_cookbook_wraps_content(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Test `prepare_cookbook` formats the template with header and content.

    Given:
        - The repository contains `python.mise.toml` with known content.
    When:
        - `prepare_cookbook("python")` is called.
    Then:
        - The returned string contains the `Generated by micoo` header.
        - The returned string contains the raw cookbook content.
        - The returned string contains the commit SHA in the remote URL.
    """
    _seed(tmp_path, ["python"])
    monkeypatch.setattr(micoo_main, "repository_path", tmp_path)
    output = micoo_main.prepare_cookbook("python")
    assert "### Generated by micoo" in output
    assert "# python" in output
    sha = Repo(tmp_path).head.commit.hexsha
    assert sha in output
