---
name: CD
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    tags:
      - "*" # Will trigger for every tag, alternative: 'v*'
jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --strip header --github-repo ${{ github.repository }}
  build:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - name: Echo
        run: echo "${{ needs.changelog.outputs.release_body }}"
      - name: Exiit
        run: exit
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Setup uv
        id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Restore cache
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
      - name: Build the Package
        run: uv build --no-sources --quiet
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: ./dist
  release:
    needs: [build, changelog]
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: Mandatory for GitHub Release (action-gh-release)
      discussions: write # IMPORTANT: Mandatory for Discussions (action-gh-release)
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        if: github.ref_type == 'tag'
        with:
          files: ./dist/*
          body: ${{ needs.changelog.outputs.release_body }}
          discussion_category_name: Announcements
  publish-pypi:
    needs: release
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    permissions:
      id-token: write # IMPORTANT: Mandatory for Trusted Publishing (gh-action-pypi-publish)
    environment:
      name: publish
      url: https://pypi.org/project/micoo/${{ github.ref_name }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
